using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Bullet : MonoBehaviour
{
    public float speed = 8.0f; //ลบพห ภฬตฟผำทย
    private Rigidbody bulletRigidbody; //ธฎม๖ตๅนูต๐ ผฑพ๐

    // Start is called before the first frame update
    void Start()
    {
        //ฐิภำ ฟภบ๊มงฦฎฟกผญ Rigidbody ฤฤฦ๗ณอฦฎธฆ รฃพฦ BullletRigidbodyฟก วาด็
        bulletRigidbody = GetComponent<Rigidbody>();
        //ธฎม๖ตๅนูต๐ภว ผำตต = ภฬตฟ ผำทย * พียส นๆวโ
        bulletRigidbody.velocity = speed * transform.forward;

        //3รสตฺฟก ภฺฝลภว ฐิภำ ฟภบ๊มงฦฎ ฦฤฑซ
        Destroy(gameObject,3f);
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
